var cloudinary = require('cloudinary').v2;

var multer  = require('multer');
var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer



exports.uploadImage = (upload.single('fileData'), (req, res,next) => {
    logger.info(req.file);//this will be automatically set by multer
    logger.info(req.body);
    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    fs.readFile(req.file.path,(err, contents)=> {
     if (err) {
     console.log('Error: ', err);
    }else{
     console.log('File contents ',contents);
     
    }
   });
  });