var cloudinary = require('cloudinary').v2;
var fs = require('fs');
var multer  = require('multer');
var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer



exports.uploadImage = (upload.single('fileData'),(req, res, next) => {
    console.log('check')
    //logger.info(req.body);//this will be automatically set by multer
    console.log(req.body);
    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    fs.readFile(req.body.path,(err, contents)=> {
     if (err) {
     console.log('Error: ', err);
    }else{
     console.log('File contents ',contents);
     res.send({
         file:contents,
         objectFile:req.file,
         msg:'hello'
     })
    }
   });
  });